### ISSUE TITLE
My request timed out, with an error of closing a connection

### ISSUE THREAD

**Issue by LtD0gE** [vercel-community/php#252]
# Question
![image](https://user-images.githubusercontent.com/88997240/172310354-3e526d04-9e27-423b-9d6b-5b63291dd29e.png)
![image](https://user-images.githubusercontent.com/88997240/172310511-a9988c97-3b56-48ed-be4a-b07cdbc12163.png)
I'm trying to deploy Typecho serverlessly on Vercel, but it timed out.

My repository: https://github.com/LtD0gE/typecho-vercel

**Comment by LtD0gE** [comment]
i set up a PHP built-in server on my codespace, and it doesn't handle requests until after 20 seconds.
do i need any extra configurations? or, some other versions like PHP 7.4?

**Comment by LtD0gE** [comment]
hello? can anyone solve?

**Comment by f3l1x** [comment]
Hi. I will take a look as soon as possible.

**Comment by f3l1x** [comment]
https://github.com/LtD0gE/typecho-vercel gets 404.

**Comment by LtD0gE** [comment]
I solved just now...
My local MySQL server is externally inaccessible, so the script is running timed out, and it becomes OK when I'm testing on my own computer.
Sorry for disturbing :)

**Comment by f3l1x** [comment]
Glad to help.
