### ISSUE TITLE
Why can't I use sqlite ? 

### ISSUE THREAD

**Issue by MliKiowa** [vercel-community/php#266]
# Question

I want to deploy typecho in vercel,but it is not working.
![IMG_20220707_133102](https://user-images.githubusercontent.com/61873808/177698836-9553ef71-9706-49a4-b5ed-152867bf3e2d.jpg)
But according to the documentation, sqlite3 is supported.Looking through typecho code ,the sqite3 extension should be supported .  Why can't I use sqlite on vercel?

**Comment by robertdrakedennis** [comment]
you most likely need to access the temp directory, but you shouldnt use SQLite as vercel will not carry over temporary files that are not included within your git repo. Use a regular database, best recommendation is planetscale.

**Comment by MliKiowa** [comment]
ok,thanks

**Comment by AncientCatz** [comment]
> ok,thanks

Does typecho run well in vercel?
