### ISSUE TITLE
Cannot send email

### ISSUE THREAD

**Issue by dionisis84** [vercel-community/php#280]
# Question

I deployed a website on Vercel with a contact form, but I cannot send emails through this form!
In the logs i get the following error:

> ERROR	🐘STDERR: sh: /usr/sbin/sendmail: No such file or directory

Is this something that I have to configure manually or a bug?

Thanks a lot

**Comment by f3l1x** [comment]
Hi, you have to use SMTP server. Sendmail is not installed.

**Comment by dionisis84** [comment]
@f3l1x Thanks a lot!
