### ISSUE TITLE
Upgrade nodejs12.x runtime

### ISSUE THREAD

**Issue by styfle** [vercel-community/php#281]
`vercel-php` is still using `nodejs12.x` under the hood which has reached End of Life.

https://github.com/vercel-community/php/blob/a9022e848b40ad9c7471b23f35fe80e69619f528/src/index.ts#L126

This should be upgraded soon to avoid new deployments from failing.

cc @f3l1x

**Comment by robertdrakedennis** [comment]
Deployments are already failing as of now, needs to be updated if possible, let me know what needs changing if there is anything I can do I'd love to help.

**Comment by LittleYang0531** [comment]
I have also encountered this error.

Yesterday I can deploy my project successfully, but today it throw this error to me.

What should I do?

**Comment by robertdrakedennis** [comment]
You may be able to fork the repo and use your own build but for not there is nothing to do but wait unfortunately

**Comment by f3l1x** [comment]
Hi folks. I will release new version asap.

**Comment by f3l1x** [comment]
@LittleYang0531 @robertdrakedennis v0.5.2 bumped.

https://www.npmjs.com/package/vercel-php
