### ISSUE TITLE
Postgres connection error - "SCRAM authentication requires libpq version 10 or above"

### ISSUE THREAD

**Issue by SchramlTim** [vercel-community/php#315]
# Bug happend in

- Version: 0.3.2 -> 0.5.2

## Description

This error happend if i try to connect to my supabase postgres database: "SCRAM authentication requires libpq version 10 or above".
Is there an option to solve this error?

**Comment by MaksOuw** [comment]
Same problem here, if you have any solution I'll take it !

**Comment by snuggneighborhood** [comment]
Same problem here.

**Comment by irfanhkm** [comment]
up, same problem

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1

**Comment by f3l1x** [comment]
Hi folks! I am not sure if there is any way to upgrade libpq to newer version, because lambdas are using Amazon Linux 2 under the hood. But, I will try to take a look deeper.

**Comment by tao** [comment]
Will this fix work? https://stackoverflow.com/a/72703748

I've been using Planetscale instead as my database temporarily and that works for now but would love to get Postgres working.

**Comment by SchramlTim** [comment]
is there an update?

**Comment by SchramlTim** [comment]
I have an update: 
Found time to work my way into the platform and found a fix for it.
The problem needs to be fixed in [libphp](https://github.com/juicyfx/libphp). I will put a PR there and hope that @f3l1x will release a new package version for everyone in time :)

**Comment by Neustradamus** [comment]
@SchramlTim: Where is the PR?
Maybe good to specify ;)

**Comment by SchramlTim** [comment]
Ofcouse

https://github.com/juicyfx/libphp/pull/376

**Comment by HugoBarjot** [comment]
Same problem too @SchramlTim  i tried to connect using PDO method with php-vercel function: https://github.com/vercel-community/php

how do i use [libphp](https://github.com/juicyfx/libphp) in my project ?

i need create this architecture in my project  just ?

├── dist
// │   └── *.js
└── native
//     ├── lib
//     │   └── * (shared libs)
//     └── php
//         ├── modules
//         │   └── *.so (php modules)
//         ├── composer
//         ├── php.ini
//         ├── php
//         ├── php-cgi
//         ├── php-fpm
//         └── php-fpm.ini

**Comment by f3l1x** [comment]
I am working on it. I need to release new version.

**Comment by f3l1x** [comment]
Hi, can you folks try new versions?

vercel-php@0.6.0 - PHP 8.2.x (https://example-php-8-2.vercel.app/)
vercel-php@0.5.3 - PHP 8.1.x (https://example-php-8-1.vercel.app/)
vercel-php@0.4.1 - PHP 8.0.x (https://example-php-8-0.vercel.app/)
vercel-php@0.3.3 - PHP 7.4.x (https://example-php-7-4.vercel.app/)

**Comment by Neustradamus** [comment]
@SchramlTim, @MaksOuw, @snuggneighborhood, @irfanhkm, @tao, @HugoBarjot: Can you try the new versions specified by @f3l1x?

**Comment by HugoBarjot** [comment]
Connection work for me with this 0.6.0 version

**Comment by SchramlTim** [comment]
Tested it too. PHP 8.2 works for me fine.

**Comment by f3l1x** [comment]
Awesome. Thank you guys for waiting and @SchramlTim for code updates.

**Comment by f3l1x** [comment]
Awesome. Thank you guys for waiting and @SchramlTim for code updates.
