### ISSUE TITLE
`intl` is not installed

### ISSUE THREAD

**Issue by tomy0000000** [vercel-community/php#367]
# Bug report

- Version: 0.5.2
- URL: https://github-readme-streak-stats-hjwvco6os-tomy0000000.vercel.app/demo/
- Repository: https://github.com/tomy0000000/github-readme-streak-stats

## Description

I am trying to deploy a fork instance of [Github Readme Streak Stats](https://github.com/tomy0000000/github-readme-streak-stats) on vercel. After 2 or 3 hours of debugging, I came to this exception saying `Class "Locale" not found`. After some googling, it appears that the runtime does not ship the `intl` extension as README had indicated.

Is this a bug? or should I setup something to install it manually?

**Comment by f3l1x** [comment]
Hi @tomy0000000. It's a bug, I need to investigate it. Thank you.

**Comment by f3l1x** [comment]
Hi, can you try new versions? It should be fixed.

vercel-php@0.6.0 - PHP 8.2.x (https://example-php-8-2.vercel.app/)
vercel-php@0.5.3 - PHP 8.1.x (https://example-php-8-1.vercel.app/)
vercel-php@0.4.1 - PHP 8.0.x (https://example-php-8-0.vercel.app/)
vercel-php@0.3.3 - PHP 7.4.x (https://example-php-7-4.vercel.app/)
