### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by kawax** [vercel-community/php#370]
# Bug report

- Version: 0.5.2. Same for 0.4.0.
- URL: No
- Repository: No

api/index.php
```php
<?php
phpinfo();
```
vercel.json
```json
{
    "outputDirectory": ".",
    "functions": {
        "api/*.php": {
            "runtime": "vercel-php@0.5.2"
        }
    }
}
```

```
> Installing Builder: vercel-php@0.5.2
--
| 🐘 Downloading user files
| 🐘 Downloading PHP runtime files
| 🐘 Creating lambda
| Error: EISDIR: illegal operation on a directory, read
```

## Description

When `First deploy` or `Redeploy without existing Build Cache.`  
This error occurs.

If a build cache exists, no error occurs.

This error does not occur in projects that do not use vercel-php.

**Comment by f3l1x** [comment]
Thank you for the report. I will take a look after holidays.

**Comment by sunxyw** [comment]
same issue here:
```
[00:25:43.642] Cloning github.com/sunxyw/yard (Branch: main, Commit: 35751b7)
[00:25:43.960] Previous build cache not available
[00:25:44.180] Cloning completed: 537.995ms
[00:25:44.708] Running "vercel build"
[00:25:45.364] Vercel CLI 28.10.0
[00:25:45.596] > Installing Builder: vercel-php@0.5.2
[00:25:50.321] 🐘 Downloading user files
[00:25:50.322] 🐘 Downloading PHP runtime files
[00:25:50.432] 🐘 Creating lambda
[00:25:51.270] Error: EISDIR: illegal operation on a directory, read
```

**Comment by MarcVegas** [comment]
> # Bug report
> * Version: 0.5.2. Same for 0.4.0.
> * URL: No
> * Repository: No
> 
> api/index.php
> 
> ```
> <?php
> phpinfo();
> ```
> 
> vercel.json
> 
> ```json
> {
>     "outputDirectory": ".",
>     "functions": {
>         "api/*.php": {
>             "runtime": "vercel-php@0.5.2"
>         }
>     }
> }
> ```
> 
> ```
> > Installing Builder: vercel-php@0.5.2
> --
> | 🐘 Downloading user files
> | 🐘 Downloading PHP runtime files
> | 🐘 Creating lambda
> | Error: EISDIR: illegal operation on a directory, read
> ```
> 
> ## Description
> When `First deploy` or `Redeploy without existing Build Cache.` This error occurs.
> 
> If a build cache exists, no error occurs.
> 
> This error does not occur in projects that do not use vercel-php.

Currently experiencing the same issue. Initially used vercel-php 0.3.2 and tried to update it to 0.5.2 but the same issue still occurs.

**Comment by kawax** [comment]
Not occurring now.

**Comment by kawax** [comment]
Maybe resolved.

**Comment by MrFriggo** [comment]
I have the same settings, and it doesn't work for me.

**Comment by leerob** [comment]
Hey there, we believe this should be fixed on the Vercel side. Please let us know! 🙏

**Comment by MrFriggo** [comment]
Thank you. It's solved.
