### ISSUE TITLE
Error: The Serverless Function "api/index" is 69.61mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size

### ISSUE THREAD

**Issue by kudarukuni** [vercel-community/php#407]
# Bug report

- Version: 0.5.2

## Description

Error: The Serverless Function "api/index" is 69.61mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size

**Comment by f3l1x** [comment]
Hi. It looks like your app is too big.
