### ISSUE TITLE
Unable to use php7.4

### ISSUE THREAD

**Issue by imlhb** [vercel-community/php#418]
# Question
I want to use the PHP 7.4 version，but prompt:“The Runtime "vercel-php@0.3.1" is using "nodejs12.x", which is discontinued. Please upgrade your Runtime to a more recent version or consult the author for more details.‘’

**Comment by f3l1x** [comment]
Hi @imlhb. I will update v0.3.x to latest runtime. Thx

**Comment by f3l1x** [comment]
Hi @imlhb 

New versions are bumped.

vercel-php@0.6.0 - PHP 8.2.x (https://example-php-8-2.vercel.app/)
vercel-php@0.5.3 - PHP 8.1.x (https://example-php-8-1.vercel.app/)
vercel-php@0.4.1 - PHP 8.0.x (https://example-php-8-0.vercel.app/)
vercel-php@0.3.3 - PHP 7.4.x (https://example-php-7-4.vercel.app/)

**Comment by fishpigbird** [comment]
Error: The Runtime "vercel-php@0.3.3" is using "nodejs14.x", which is discontinued. Please upgrade your Runtime to a more recent version or consult the author for more details.
