### ISSUE TITLE
how to deploy swoole or workerman to vercel ?

### ISSUE THREAD

**Issue by askme-gpt** [vercel-community/php#429]
# Question
how to deploy swoole or workerman to vercel ? https://github.com/walkor/workerman

my application is based on workerman framework,it called webman. it's start the serve like this blow : 
```php
php start.php start -d
```
then ,it will listen on a port ,like 7878, and how to deploy  this kind of application on vercel ?

**Comment by f3l1x** [comment]
Hi, unfortunately workerman is not supported. You can use swoole, but in non server mode.

**Comment by askme-gpt** [comment]
thanks for your answer. I wonder is there a plan for workerman ? if I can make my project into a .phar file ,is there a chance to deploy it ? just like 
````php
php webman.phar start
```

**Comment by f3l1x** [comment]
I think serverless is not good way to run workerman.
