### ISSUE TITLE
Authentication Using Firebase Admin SDK for PHP

### ISSUE THREAD

**Issue by denusklo** [vercel-community/php#430]
After deployment on vercel and tried to login to my apps, it shows the below message:

`
The token is invalid: file_put_contents(/var/task/user/storage/framework/cache/data/24/fc/24fc69d48eaa682f929a7045e8f4700237c0083e): Failed to open stream: No such file or directory
`

Is this because of the php runtime trying to write files on vercel but it has no permission or what?

**Comment by f3l1x** [comment]
Yes. You have to use `/tmp` for cache or logs.

**Comment by denusklo** [comment]
Can you suggest any ways to handle that?

is it add cache handler at `vercel.json` `env` field?

![image](https://user-images.githubusercontent.com/79653229/230255728-90f1bf2d-33fb-4ef3-a495-067f7672e756.png)

**Comment by f3l1x** [comment]
Using ENV is great way. Is it working correctly?

**Comment by denusklo** [comment]
![image](https://user-images.githubusercontent.com/79653229/230776974-104c635b-4923-4b12-9a58-abcc04874a33.png)

I have added cache path, but now the session is missing when I try to assess `$_SESSION`, where should session path locate?

**Comment by denusklo** [comment]
![image](https://user-images.githubusercontent.com/79653229/230782222-64b12169-9be9-42cc-ac6d-5c9432de934c.png)

the session and cache path I set.

but got this error 

![image](https://user-images.githubusercontent.com/79653229/230782248-5d75d38b-3a54-46d2-8a0b-2ac5b46b1520.png)


to solve this error I have tried to set `build scripts` at `package.json` to
- make new folder `tmp/sessions
- set the permission
- and list all file at `/tmp` folder (below is the vercel build log)
![image](https://user-images.githubusercontent.com/79653229/230782364-4603f0c8-69ea-42d8-9047-57bc9e826a0f.png)

Which step did I did wrong, is it the path for sessions is set wrong?

**Comment by f3l1x** [comment]
There is only `/tmp` path. If you need deeper structure, you have to create somehow. For example `/tmp/sessions`, because php will not create `/tmp/sessions` itself.
