### ISSUE TITLE
How to enable php session

### ISSUE THREAD

**Issue by areaboy** [vercel-community/php#468]
Here is my **vercel.json** file

```

{
  "functions": {
    "api/*.php": {
      "runtime": "vercel-php@0.6.0"
    }
  },
  "routes": [
    { "src": "/api/(.*)",  "dest": "/index.php" }
  ]
}
```

here is my session script
**api/session1.php**

```
<?php
  
session_start();
$_SESSION['user'] = 'Ann Cooler';
  
?>
```

**api/session2.php**

```
<?php
  
session_start();
echo $_SESSION['user'];
  
?>
```

The session is  not working at all

**Comment by f3l1x** [comment]
Hi @areaboy. It's a feature, when you request your different lambdas they have different user space. You can imagine them like different docker containers. You need to use some shared space, for example redis, if you need multiple lambdas. Or you can use one lambda (one index.php) and require different `session.php` file according routes.

**Comment by areaboy** [comment]
Thanks for getting back to me. Please do you have a php sample code  and vercel.json sample configuration. Am New to Vercel.  Thanks

**Comment by denusklo** [comment]
I have encouter this issue before but I end up using databse as session driver. just need to provide your db credential and `SESSION_DRIVER=database` is fine

**Comment by Transyfor** [comment]
How would I go about doing that? I'm very new to php and Vercel so I don't fully understand where to write that. Thank you

**Comment by denusklo** [comment]
@Transyfor the place for me to put db credential and `SESSION_DRIVER=database` is file `.env` at the root directory

**Comment by urbanwatch** [comment]
same problem

**Comment by 484869326** [comment]
suggest  
   'driver' => env('SESSION_DRIVER', 'file'),
replace
   'driver' => env('SESSION_DRIVER', 'cookie'),

**Comment by f3l1x** [comment]
Sessions are allowed to use in Vercel Functions, but you need to use `/tmp` folder for them.
