### ISSUE TITLE
PHP GMP extension missing

### ISSUE THREAD

**Issue by SanjaySRocks** [vercel-community/php#507]
# Bug report
![image](https://github.com/vercel-community/php/assets/30376256/c8412dce-1ca3-4617-8cb5-6fc92a82f8e4)

- Version: 0.6.0
- URL: https://steam-finder-one.vercel.app/76561197960788468
- Repository: https://github.com/SanjaySRocks/SteamFinder

## Description

Error: Call to undefined function gmp_init()
My laravel application uses gmp module so when i installed the app on vercel it throw this error. Please check.

Check screenshot for error

**Comment by f3l1x** [comment]
Duplicate https://github.com/vercel-community/php/issues/506
