### ISSUE TITLE
NPM install errors since start of 2024

### ISSUE THREAD

**Issue by matthewruttley** [vercel-community/php#512]
# Bug report

- Version: 0.6.0
- URL: (can show privately if needed)
- Repository: (can show privately if needed)

## Description

(x-posted from here: https://github.com/orgs/vercel/discussions/5498)

On a simple hobby site I run, I had a working vercel-php installation (see below for redacted version).
This was totally fine and last deployed about 50 days ago, worked very well. I tried to push a small text update, and now all builds fail with:

`Error: Please install npm before continuing`

I've tried adding  `"installCommand": "npm install"` to the json, and also explicitly adding an override `npm install` in the project settings, but neither work, just the same error.

This is super annoying and unexpected. I don't see any recent change in the changelogs that could have caused this as well so perhaps its something related to vercel.com. However I thought it worth asking here as well. How can I fix this?

```
{
    "version": 2,
    "functions": {
        "api/index.php": {
            "runtime": "vercel-php@0.6.0"
        }
    },
    "rewrites": [
      {
        "source": "/some_page",
        "destination": "/api/something_etc.php"
      },
    ]
}
```

```
[17:45:24.778] Running build in Washington, D.C., USA (East) – iad1
[17:45:25.260] Cloning github.com/matthewruttley/my-site (Branch: main, Commit: [redacted])
[17:45:25.269] Skipping build cache, deployment was triggered without cache.
[17:45:26.307] Cloning completed: 1.046s
[17:45:26.569] Running "vercel build"
[17:45:27.038] Vercel CLI 33.1.0
[17:45:27.202] > Installing Builder: vercel-php@0.6.0
[17:45:27.213] Error: Please install `npm` before continuing
[17:45:27.213] Learn More: https://vercel.link/builder-dependencies-install-failed
```

(the doc link provided on the last line isn't helpful at all - just says I need NPM, but not how to make sure it is included further than the attempts I've mentioned above)

**Comment by abdipr** [comment]
I also experienced the same thing, does anyone know how to fix it?

**Comment by revance-digital** [comment]
Our test applications worked great until these updates. 

Now we get a PHP fatal error:
Fatal error: Uncaught Error: Call to undefined function curl_init() 

Was this removed from the PHP function?

**Comment by f3l1x** [comment]
Hi folks. I am currently investigating it.

**Comment by f3l1x** [comment]
Hi again. Please upgrade to latest versions, it should work properly.

- `vercel-php@0.6.1` - Node 18.x / PHP 8.2.x (https://example-php-8-2.vercel.app)
- `vercel-php@0.5.4` - Node 18.x / PHP 8.1.x (https://example-php-8-1.vercel.app)
- `vercel-php@0.4.3` - Node 18.x / PHP 8.0.x (https://example-php-8-0.vercel.app)
- `vercel-php@0.3.5` - Node 18.x / PHP 7.4.x (https://example-php-7-4.vercel.app)

**Comment by matthewruttley** [comment]
Hi @f3l1x thanks for looking into this. It is now working. How can I be aware of breaking changes like this in the future?

**Comment by f3l1x** [comment]
I am not 100% sure how to avoid it. I am trying my bests. :-)
