### ISSUE TITLE
mongodb module missing in 0.7.0

### ISSUE THREAD

**Issue by fascinated** [vercel-community/php#525]
# Bug report

- Version: 0.7.0

## Description

The mongodb package is missing from the 0.7.0 builds. 

You can see that it does not appear in the phpinfo output: https://example-php-8-3.vercel.app/, but present here: https://example-php-8-1.vercel.app/ (and in 0.6.0 specifically).

**Comment by f3l1x** [comment]
Hi, will take a look thanks for the report.

**Comment by f3l1x** [comment]
Hi, mongodb is supported in latest version 0.7.3.
