### ISSUE TITLE
Change / Appoint php version

### ISSUE THREAD

**Issue by qkqpttgf** [vercel-community/php#531]
# Question
1. I found that, each time vercel-php updated, a web page build with the old version will error or a white page.
Can the deployment auto update to new runtime?

2. I knew vercel-php is based on Node 18.x, but the vercel-php runtime appoint the php version 8.3,
I mean, can we use the "runtime": "vercel-php@0.7.0", and then appoint "phpVersion": "5.4.16" at somewhere?

thanks

**Comment by f3l1x** [comment]
Hi, you can use these versions.

vercel-php@0.7.0 - Node 18.x / PHP 8.3.x (https://example-php-8-3.vercel.app/)
vercel-php@0.6.1 - Node 18.x / PHP 8.2.x (https://example-php-8-2.vercel.app/)
vercel-php@0.5.4 - Node 18.x / PHP 8.1.x (https://example-php-8-1.vercel.app/)
vercel-php@0.4.3 - Node 18.x / PHP 8.0.x (https://example-php-8-0.vercel.app/)
vercel-php@0.3.5 - Node 18.x / PHP 7.4.x (https://example-php-7-4.vercel.app/)

**Comment by qkqpttgf** [comment]
Hello,
I knew this versions.
But, 0.6.1 these days make my web a BLANK page.
Or, you mean I should build a new deploy with 0.6.1?

Another,
I remember that, last year (about Aug 2023), when Node 14->Node 18, it can not update Node version via overlay the project, it must delete the project then deploy with new vercel-php. see this https://github.com/qkqpttgf/OneManager-php/issues/701 .
So, I think overlay can not update something.

**Comment by qkqpttgf** [comment]
Hello, HELP!
new ERROR today.
`
    "errorCode": "NOW_SANDBOX_WORKER_INVALID_RUNTIME",
    "errorLink": "https://vercel.com/guides/serverless-function-contains-invalid-runtime-error",
    "errorMessage": "The following Serverless Functions contain an invalid \"runtime\":\n - api/index (nodejs18.x)",
    "errorStep": "mainSub:build",
`
I can not deploy now.

**Comment by f3l1x** [comment]
New version 0.7.1 released.
