### ISSUE TITLE
Vercel 0.7.0 + Laravel 10

### ISSUE THREAD

**Issue by bykeat** [vercel-community/php#533]
# Question

Hey guys, I am trying to setup the Laravel. 

Unfortunately, the smooth journey ends when I am trying to run migration via route to trigger Artisan::call('migrate --force'). The default migration script did run but with error below on Neon Postgres DB:
`SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block (Connection: pgsql, SQL: alter table "users" add constraint "users_email_unique" unique ("email"))`

I looked into the database and found that the users table did not create. If I tried on my local Postgres DB it didn't behave such a way.

Also, I noticed there is API limit of 50MB, barebone deployment already shaved 41.6MB. I can guess it is not suit for production if the system upscales in the future?

Appreciate for some advice if anyone able to get through this. Thanks in advance.

**Comment by BernieLorbis** [comment]
I'm facing same issue

**Comment by thedanmwangi** [comment]
Looking at this in September. Still the same issue.

I don't think Vercel's serverless database provided by Neon is configured to optimally work with PHP (Laravel).

![image](https://github.com/user-attachments/assets/98cbea67-6d12-4916-a214-22bb20a93639)

**Comment by e2corporation** [comment]
When using Neon PostgreSQL, the **NON-POOLING** **Database URI** should be used. https://neon.tech/docs/guides/laravel-migrations

PHP Artisan `migrate` should run successfully when using the non-pooling connection.

```
Neon supports both direct and pooled database connection strings, which can be copied from the Connection Details widget on your Neon Project Dashboard. A pooled connection string connects your application to the database via a PgBouncer connection pool, allowing for a higher number of concurrent connections. However, using a pooled connection string for migrations can be prone to errors. For this reason, we recommend using a direct (non-pooled) connection when performing migrations. For more information about direct and pooled connections, see [Connection pooling](https://neon.tech/docs/connect/connection-pooling).
```
