### ISSUE TITLE
PHP Built-In Server HTTP error: Error: connect ECONNREFUSED 127.0.0.1:8000

### ISSUE THREAD

**Issue by wnsite** [vercel-community/php#541]
Hey, I was testing this package and I set up the example and I got this error: PHP Built-In Server HTTP error: Error: connect ECONNREFUSED 127.0.0.1:8000. The vercel deployed but when I visit the website it shows that error.
NOTE: I deployed it all using GitHub and vercel online, I did not install Node.JS or the Vercel CLI on my local machine. Do I need to do that?
The site if you want to see for yourself: https://testvercelphp.vercel.app/
My test file structure:
vercel.json
api/
├─ index.php

vercel.json:
{
  "functions": {
    "api/index.php": {
      "runtime": "vercel-php@0.7.1"
    }
  },
  "routes": [
    { "src": "/(.*)", "dest": "/api/index.php" }
  ]
}

index.php:
<?php declare(strict_types = 1);

phpinfo(INFO_ALL & ~INFO_ENVIRONMENT & ~INFO_CONFIGURATION & ~INFO_VARIABLES);

**Comment by wnsite** [comment]
Fixed! Changed the json to:
```
{
  "functions": {
    "api/index.php": {
      "runtime": "vercel-php@0.7.1"
    }
  },
  "routes": [
    { "src": "/(.*)", "dest": "/api/index.php" }
  ]
}
```

**Comment by qkqpttgf** [comment]
sorry, but where is the different

**Comment by taimaiduc** [comment]
Same error here

**Comment by vvalentim** [comment]
I was able to deploy the basic examples by setting Node.js version to 18.x on Vercel's project settings, I've tried `vercel-php@0.7.1`, `vercel-php@0.6.2` and `vercel-php@0.5.5` with it and it seems fine. 

I had the same error `PHP Built-In Server HTTP error: Error: connect ECONNREFUSED 127.0.0.1:8000` when using the default version (Node.js 20.x).

**Comment by taimaiduc** [comment]
The same just want to write comment.
Node 18 will work.

**Comment by f3l1x** [comment]
Hi folks. Node 20.x seems to be problem. I need to investigate it.

**Comment by joesandiroz2** [comment]
i get error
my web : https://doodplay.vercel.app/
my vercel id : QuBwX4iGVFwYPpmEJApy8H3L

how to fix it

**Comment by rhtm123** [comment]
I had the same problem with node 20x. I created package.json file and add this code to use node 18x version. 

package.json
`{
    "engines": {
    "node": "18.x"
    }
}`

The project is running without any issue

**Comment by chengfeng30121** [comment]
I had the same problem.
How can I fix it?

**Comment by YNSTakeru** [comment]
I managed to get it working by changing the Node.js Version in the Settings -> General on Vercel web page.

**Comment by SrivastavaArjit** [comment]
Did anyone find the solution I am facing the same error.

My file structure is as follows
![Screenshot 2024-05-16 163147](https://github.com/vercel-community/php/assets/82926673/dfec9ea7-da6c-4432-a3fd-dce5f361cb12)

and my vercel.json file is 
![Screenshot 2024-05-16 163245](https://github.com/vercel-community/php/assets/82926673/5e2e43ee-13f6-49f3-8ec1-36300684826b)

I know I haven't defined the routes for all the api's but the index route is also not working.

**Comment by SrivastavaArjit** [comment]
Ho

> Are you using Node 18.x? Node 20.x is a problem.

how can i know which one I am using?

**Comment by SrivastavaArjit** [comment]
this solution works! thanks

> I had the same problem with node 20x. I created package.json file and add this code to use node 18x version.
> 
> package.json `{ "engines": { "node": "18.x" } }`
> 
> The project is running without any issue

**Comment by SrivastavaArjit** [comment]
I know Vercel uses Node.js to build our project and for the creation of Serverless Functions but I didn't quite understand the role of "runtime":"vercel-php@0.7.1"

An explanation would be greatly appreciated.
Thank you

**Comment by imdsamimakhter** [comment]
**vercel.json**-
```
{
  "functions": {
    "api/index.php": {
      "runtime": "vercel-php@0.7.1"
    }
  },
  "routes": [
    { "src": "/(.*)", "dest": "/api/index.php" }
  ]
}
```

**package.json**-
`{ "engines": { "node": "18.x" } }`

### **Works** 👍

**Comment by zengboin** [comment]
The error is：
```
Spawning: PHP Built-In Server at /var/task/user (document root) and /var/task/user/api/index.php (router)
🐘STDERR: php: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
```
Node 20x image has no libssl.so.10

**Comment by thedoggybrad** [comment]
> The error is：
> 
> ```
> Spawning: PHP Built-In Server at /var/task/user (document root) and /var/task/user/api/index.php (router)
> 🐘STDERR: php: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
> ```
> 
> Node 20x image has no libssl.so.10

I have seen that the Node.js 18 will be retired on Vercel next year (Early 2025). 
By the way, how important is libsssl.so in PHP? (I am just a beginner in PHP)
https://vercel.com/docs/functions/runtimes/node-js#node.js-version
![Screenshot 2024-07-02 130534](https://github.com/vercel-community/php/assets/94173621/d21540fb-6a2f-435d-b96d-8e357fd8f2f7)

**Comment by zengboin** [comment]
> > The error is：
> > ```
> > Spawning: PHP Built-In Server at /var/task/user (document root) and /var/task/user/api/index.php (router)
> > 🐘STDERR: php: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Node 20x image has no libssl.so.10
> 
> I have seen that the Node.js 18 will be retired on Vercel next year (Early 2025). By the way, how important is libsssl.so in PHP? (I am just a beginner in PHP) https://vercel.com/docs/functions/runtimes/node-js#node.js-version ![Screenshot 2024-07-02 130534](https://private-user-images.githubusercontent.com/94173621/344883345-d21540fb-6a2f-435d-b96d-8e357fd8f2f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNjY5MTgsIm5iZiI6MTcyMTI2NjYxOCwicGF0aCI6Ii85NDE3MzYyMS8zNDQ4ODMzNDUtZDIxNTQwZmItNmEyZi00MzVkLWI5NmQtOGUzNTdmZDhmMmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDAxMzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NjNjNTEwMzZiNTY5ZjA2MTY4NGZmYzgxNzBlZGMzYWZkN2JmZTM2ODM4MGU4MDEyNTgxOGU1MWVkMTcwYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w2Cvgn_3u8ENApiKCnd62p_Wkj8VSAVLNu6CWRpFvnM)

PHP use libssl.so in `curl` extension and `openssl` extension.
using `curl` to request the https website

**Comment by sekedus** [comment]
This solution worked for me:
```json
{
  "functions": {
    "api/index.php": {
      "runtime": "vercel-php@0.3.6"
    }
  },
  "rewrites": [
    { "source": "/(.*)", "destination": "/api/index.php" }
  ]
}
```

And change node.js version to `18.x` : [#504](https://github.com/vercel-community/php/issues/504#issuecomment-2024215402)

**Comment by thedoggybrad** [comment]
> > > The error is：
> > > ```
> > > Spawning: PHP Built-In Server at /var/task/user (document root) and /var/task/user/api/index.php (router)
> > > 🐘STDERR: php: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Node 20x image has no libssl.so.10
> > 
> > I have seen that the Node.js 18 will be retired on Vercel next year (Early 2025). By the way, how important is libsssl.so in PHP? (I am just a beginner in PHP) https://vercel.com/docs/functions/runtimes/node-js#node.js-version ![Screenshot 2024-07-02 130534](https://private-user-images.githubusercontent.com/94173621/344883345-d21540fb-6a2f-435d-b96d-8e357fd8f2f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNjY5MTgsIm5iZiI6MTcyMTI2NjYxOCwicGF0aCI6Ii85NDE3MzYyMS8zNDQ4ODMzNDUtZDIxNTQwZmItNmEyZi00MzVkLWI5NmQtOGUzNTdmZDhmMmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDAxMzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NjNjNTEwMzZiNTY5ZjA2MTY4NGZmYzgxNzBlZGMzYWZkN2JmZTM2ODM4MGU4MDEyNTgxOGU1MWVkMTcwYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w2Cvgn_3u8ENApiKCnd62p_Wkj8VSAVLNu6CWRpFvnM)
> 
> PHP use libssl.so in `curl` extension and `openssl` extension.
> using `curl` to request the https website



So with no libssl.so, basically CURL will be dead right?

**Comment by Kenny1291** [comment]
Why is not is not specified in the readme that Node 18.x must be selected?

**Comment by Bfaschat** [comment]
For anyone still faced with this issue, do the following

## Step 1: Use a working example 

[PHP - fast & simple](https://github.com/juicyfx/vercel-examples/tree/master/php/)

Step 2: replace the `api/index.php` file content with this

```
<?php
phpinfo();
```

Step 3: Switch from Node 20.x to Node 18.x under vercel settings

![image](https://github.com/user-attachments/assets/c2187891-71ac-4484-957c-26f53571ec67)


Step 4: Redeploy your project and Voila!!!

![image](https://github.com/user-attachments/assets/09c85c82-598f-4439-9904-bfbae2a8fa3f)

Enjoy!!!

**Comment by f3l1x** [comment]
Hey all! It should be fixed to use Node 20.x, can you folks try version `0.7.2` with Node 20.x?

https://example-php-8-3.vercel.app/
