### ISSUE TITLE
Can we increase the **max_execution_time** and **post_max_size** here?

### ISSUE THREAD

**Issue by imdsamimakhter** [vercel-community/php#547]
# Question

Can we increase the **max_execution_time** and **post_max_size** here?

**Comment by AngelAlexQC** [comment]
Yes, you can override your php.ini file, read the 5th item of FAQ:
https://github.com/vercel-community/php?tab=readme-ov-file#%EF%B8%8F-faq

**Comment by f3l1x** [comment]
Yep, @AngelAlexQC is correct.
