### ISSUE TITLE
php: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by giorbismiguel** [vercel-community/php#560]
# Bug report

- Version: 34.1.8
- URL: No
- Repository:  No

## Description
When i try to deploy a Laravel project the deploying is failed
 with the following error:
php: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory

![image](https://github.com/vercel-community/php/assets/2695637/09d675fe-8838-48fc-9d8a-20a87e9cb0a3)

**Comment by bakomon** [comment]
Check [#504 comment](https://github.com/vercel-community/php/issues/504#issuecomment-2024215402)

**Comment by sekedus** [comment]
Check [#504 comment](https://github.com/vercel-community/php/issues/504#issuecomment-2024215402)

**Comment by nadar** [comment]
duplicated #566

**Comment by f3l1x** [comment]
Hi, it should be fixed, can you try version `0.7.2`?

https://example-php-8-3.vercel.app/
