### ISSUE TITLE
Vercel Environment Variables

### ISSUE THREAD

**Issue by BOXNYC** [vercel-community/php#567]
# Question

How do I access the Vercel Project's env vars in PHP? I tested:
```
<?php
print_r( $_ENV );
?>
```
And the variables I input to the project settings aren't there.

Thanks!

**Comment by f3l1x** [comment]
Hi, can you gest `getenv()` (https://www.php.net/manual/en/function.getenv.php) or `$_SERVER` variable?

**Comment by BOXNYC** [comment]
getenv() worked, thanks so much!
