### ISSUE TITLE
could not find driver (Connection: pgsql, .... on version 0.7.3

### ISSUE THREAD

**Issue by suebphattana** [vercel-community/php#572]
# Bug report

- Version: 0.7.3

## Description
I found similar problem to #515 but it happens with the latest version (0.7.3).

// config/database.php
```
'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DB_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'laravel'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => env('DB_CHARSET', 'utf8'),
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            // 'sslmode' => 'prefer',
            'sslmode' => 'require',
        ],
```

This is my quite first time posting issues on Github. I apologize in advance for any mistakes/bad manners.

Error image:
<img width="1113" alt="Screenshot_6" src="https://github.com/user-attachments/assets/ca355335-7a57-455a-ba95-bf379ec0b5d2">

ENV on Vercel project settings:
<img width="733" alt="Screenshot_8" src="https://github.com/user-attachments/assets/31a5fb45-91b2-43b2-89ba-56ae3b983a5b">

**Comment by f3l1x** [comment]
Hi @suebphattana. I do not know what that error means. Driver pgsql is supported.

https://example-php-8-3.vercel.app/

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/ae6a668f-94af-489a-8f08-f44910a2310f">

**Comment by suebphattana** [comment]
> Hi @suebphattana. I do not know what that error means. Driver pgsql is supported.
> 
> https://example-php-8-3.vercel.app/
> 
> <img alt="image" width="1031" src="https://private-user-images.githubusercontent.com/538058/378294453-ae6a668f-94af-489a-8f08-f44910a2310f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDE1MzIsIm5iZiI6MTcyOTUwMTIzMiwicGF0aCI6Ii81MzgwNTgvMzc4Mjk0NDUzLWFlNmE2NjhmLTk0YWYtNDg5YS04ZjA4LWY0NDkxMGEyMzEwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwOTAwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmE0YThhNjYzZmU0NTdhZWU1ZTVmOTdjZDMxYTU0ZjE0MjM0ZDc2ZThmYjkxYThiYjE5NTIwOWEyZTdhMmQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xg6BU5_pYrYQ02EGm3Vy3tyUDue5Y2mgXef9zfZhMh4">

Hi, thank you for your reply. I looked into the link https://example-php-8-3.vercel.app/ you gave me. I see pgsql in there and I can confirm that it somehow looks different than mine, which does not has pgsql enabled, only mysql (from my understanding) : [https://koki.bcd.academy/phpinfo](url) (don't worry about current DB password there, i'll change later)

I made a switch to use mysql instead of Postgres, and it works right away. Does that mean no pgsql enabled on my Vercel PHP project?

However, I continue to run project, and found out there's a problem about cURL extension too (like it is also not enabled, or some functions are missing from it):

<img width="1121" alt="Screenshot_9" src="https://github.com/user-attachments/assets/4aa535b2-d632-4a9c-8659-fe2c49b47955">

I also tried enabling them manually via `api/php.ini` but still no luck
```
extension=pgsql
extension=pdo_pgsql
extension=curl
memory_limit = 128M
post_max_size = 20M
```

thanks

**Comment by tao** [comment]
Try use node version 18 to get the postgres driver to load: https://github.com/vercel-community/php/issues/555#issuecomment-2423948239
